### ISSUE TITLE
Atom goes mad when package is enabled

### ISSUE THREAD

**Issue by andya9** [AtomLinter/linter-xmllint#13]
Atom (v 0.201) goes crazy when xmllint is enabled and detects errors: when I put the cursor on the affected line and try to edit it weird things happen. Such as: copy-paste stops working; pressing < and > clones text beside cursor; clicking backspace pops up this error:

/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:683
Hide Stack Trace
TypeError: Cannot read property 'start' of undefined
  at Function.module.exports.Range.fromObject (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/range.js:35:31)
  at Range.module.exports.Range.compare (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/range.js:185:32)
  at Marker.module.exports.Marker.emitChangeEvent (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/marker.js:362:156)
  at Marker.module.exports.Marker.update (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/marker.js:335:12)
  at Marker.module.exports.Marker.setProperties (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/marker.js:229:19)
  at Marker.module.exports.Marker.setProperties (/usr/share/atom/resources/app.asar/src/marker.js:98:32)
  at Selection.module.exports.Selection.clear (/usr/share/atom/resources/app.asar/src/selection.js:199:19)
  at Cursor.module.exports.Cursor.clearSelection (/usr/share/atom/resources/app.asar/src/cursor.js:653:55)
  at Cursor.module.exports.Cursor.changePosition (/usr/share/atom/resources/app.asar/src/cursor.js:680:12)
  at Cursor.module.exports.Cursor.setBufferPosition (/usr/share/atom/resources/app.asar/src/cursor.js:134:19)
  at Selection.module.exports.Selection.deleteSelectedText (/usr/share/atom/resources/app.asar/src/selection.js:562:81)
  at Selection.module.exports.Selection.backspace (/usr/share/atom/resources/app.asar/src/selection.js:489:19)
  at /usr/share/atom/resources/app.asar/src/text-editor.js:758:26
  at /usr/share/atom/resources/app.asar/src/text-editor.js:771:29
  at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:678:18)
  at TextEditor.module.exports.TextEditor.transact (/usr/share/atom/resources/app.asar/src/text-editor.js:1132:26)
  at /usr/share/atom/resources/app.asar/src/text-editor.js:765:24
  at TextEditor.module.exports.TextEditor.mergeSelections (/usr/share/atom/resources/app.asar/src/text-editor.js:1950:43)
  at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/usr/share/atom/resources/app.asar/src/text-editor.js:1924:35)
  at TextEditor.module.exports.TextEditor.mutateSelectedText (/usr/share/atom/resources/app.asar/src/text-editor.js:763:19)
  at TextEditor.module.exports.TextEditor.backspace (/usr/share/atom/resources/app.asar/src/text-editor.js:757:19)
  at TextEditor.atom.commands.add.stopEventPropagationAndGroupUndo.core:backspace (/usr/share/atom/resources/app.asar/src/text-editor-element.js:425:19)
  at /usr/share/atom/resources/app.asar/src/text-editor-element.js:305:34
  at TextBuffer.module.exports.TextBuffer.transact (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:678:18)
  at TextEditor.module.exports.TextEditor.transact (/usr/share/atom/resources/app.asar/src/text-editor.js:1132:26)
  at atom-text-editor.newCommandListeners.(anonymous function) (/usr/share/atom/resources/app.asar/src/text-editor-element.js:304:22)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:238:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:178:20)

**Comment by andya9** [comment]
I tried other linters and they work fine, so its a problem of this package, not of atom-linter

**Comment by andya9** [comment]
@steelbrain 
Could you please try this gist to test if the bug affects you too?
  https://gist.github.com/andya9/10f878e8048b0a52f83c

Steps:
1. bracket-matcher installed and enabled (but if it isn’t, the error will still popup blaming autocomplete-plus, git-diff or atom itself)
2. delete \> from the first section element. 
3. Place the cursor inside the paragraph element
4. place the cursor where you deleted \>
5. press > (on my keyboard: shift+<): the error should appear
Please do mind that this doesn’t happen everytime: in this case, try replacing 3. with:
3bis. Place the cursor inside block, then book, then paragraph (and so on)

**Comment by andya9** [comment]
I’m closing this in favor of https://github.com/AtomLinter/Linter/issues/560
