### ISSUE TITLE
Uncaught Error: Attribute without value

### ISSUE THREAD

**Issue by nelson6e65** [AtomLinter/linter-xmllint#54]
I'm getting this error on Atom `1.6.2` when I try to edit any xml file:

```
TypeError: XRegExp is not a function
    at Object.module.exports.parseMessages (file:///C:/Users/nmartell/.atom/packages/linter-xmllint/lib/init.coffee:221:13)
    at file:///C:/Users/nmartell/.atom/packages/linter-xmllint/lib/init.coffee:68:21
    at process._tickCallback (node.js:368:9)
```

**Comment by dirk-thomas** [comment]
What version of `linter-xmllint` are you using? What platform are you on? How did you install the package?

According to the code the package depends on `xregexp` (https://github.com/AtomLinter/linter-xmllint/blob/e2f14936c0871bc07b948914886b4b090f6fa59a/package.json#L16) and requires it correctly (https://github.com/AtomLinter/linter-xmllint/blob/e2f14936c0871bc07b948914886b4b090f6fa59a/lib/init.coffee#L219) before the line which doesn't find it for you.

**Comment by Arcanemagus** [comment]
Have you tried re-installing the package? `apm` sometimes fails to properly install all necessary dependencies.

**Comment by nelson6e65** [comment]
I did installed from Settings panel.

**Atom Version**: 1.6.2
**System**: Windows 10
[linter-xmllint](https://github.com/AtomLinter/linter-xmllint) v1.3.4

But... I uninstall `linter-xmllint` and `linter` and restart Atom and apparently is solved. But... I have another problem... Maybe related to install or 
> apm sometimes fails to properly install all necessary dependencies.

![ss](https://cloud.githubusercontent.com/assets/9272498/14467681/360a1454-00a6-11e6-803b-56532537853a.png)

### Stack Trace

Uncaught Error: Attribute without value
Line: 2
Column: 13
Char: m

```
At events.js:141

Error: Attribute without value
Line: 2
Column: 13
Char: m
    at error (C:\Users\nmartell\.atom\packages\linter-xmllint\node_modules\sax\lib\sax.js:667:10)
    at strictFail (C:\Users\nmartell\.atom\packages\linter-xmllint\node_modules\sax\lib\sax.js:693:7)
    at Object.write (C:\Users\nmartell\.atom\packages\linter-xmllint\node_modules\sax\lib\sax.js:1353:13)
    at SAXStream.write (C:\Users\nmartell\.atom\packages\linter-xmllint\node_modules\sax\lib\sax.js:239:18)
    at ReadableString.ondata (_stream_readable.js:525:20)
    at emitOne (events.js:77:13)
    at ReadableString.emit (events.js:169:7)
    at ReadableString.Readable.read (_stream_readable.js:360:10)
    at flow (_stream_readable.js:733:26)
    at resume_ (_stream_readable.js:713:3)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```

### Commands

```
     -6:40.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -6:37.6.0 core:undo (atom-text-editor.editor.is-focused)
     -6:36 core:move-left (atom-text-editor.editor.is-focused.autocomplete-active)
     -6:34.9.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -3:56 core:save (atom-text-editor.editor.is-focused)
     -0:15.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:13.7.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "php-debug"
    ]
  },
  "linter-xmllint": {}
}
```

### Installed Packages

```coffee
# User
atom-text-transformer, v0.7.0
auto-detect-indentation, v1.0.0
auto-indent, v0.5.0
autoclose-html, v0.23.0
autocomplete-php, v0.3.7
docblockr, v0.7.3
docs-snippets, v0.8.0
html-entities, v0.4.0
indentation-indicator, v0.6.0
language-blade, v0.24.1
language-latte, v0.3.1
line-ending-converter, v1.3.2
linter, v1.11.4
linter-bootlint, v1.0.2
linter-coffeelint, v1.1.2
linter-csslint, v1.3.2
linter-pep8, v1.2.1
linter-php, v1.2.0
linter-phpcs, v1.3.2
linter-xmllint, v1.3.4
minimap, v4.21.0
sync-settings, v0.7.2

# Dev
No dev packages
```

**Comment by dirk-thomas** [comment]
@nelson6e65 Are you still experiencing this problem?

I tried the case you described (an attribute without a value) and get the proper marker `Specification mandate value for attribute xxx`. It might be dependent on the `sax` version? Can you please check which one you are using (`~/.atom/packages/linter-xmllint/node_modules/sax/package.json`). If you uninstall and reinstall the package you should get version 1.2.1 of sax. Maybe that helps?

**Comment by nelson6e65** [comment]
@dirk-thomas I'm not in Windows right now, but seems solved.

I'm on Fedora 24 (x86), **Atom** `v1.10.0`, **linter-xmllint:** `v1.3.6`, and i I'm not getting any error :smiley:. 

#### Content of `~/.atom/packages/linter-xmllint/node_modules/sax/package.json`: 
```json
{
  "_args": [
    [
      {
        "raw": "sax@^1.1.4",
        "scope": null,
        "escapedName": "sax",
        "name": "sax",
        "rawSpec": "^1.1.4",
        "spec": ">=1.1.4 <2.0.0",
        "type": "range"
      },
      "/tmp/d-11685-2562-158z6dv/package.tgz"
    ]
  ],
  "_from": "sax@>=1.1.4 <2.0.0",
  "_id": "sax@1.2.1",
  "_inCache": true,
  "_installable": true,
  "_location": "/linter-xmllint/sax",
  "_nodeVersion": "5.6.0",
  "_npmOperationalInternal": {
    "host": "packages-13-west.internal.npmjs.com",
    "tmp": "tmp/sax-1.2.1.tgz_1458360406158_0.19482766138389707"
  },
  "_npmUser": {
    "name": "isaacs",
    "email": "i@izs.me"
  },
  "_npmVersion": "3.7.3",
  "_phantomChildren": {},
  "_requested": {
    "raw": "sax@^1.1.4",
    "scope": null,
    "escapedName": "sax",
    "name": "sax",
    "rawSpec": "^1.1.4",
    "spec": ">=1.1.4 <2.0.0",
    "type": "range"
  },
  "_requiredBy": [
    "/linter-xmllint"
  ],
  "_resolved": "https://registry.npmjs.org/sax/-/sax-1.2.1.tgz",
  "_shasum": "7b8e656190b228e81a66aea748480d828cd2d37a",
  "_shrinkwrap": null,
  "_spec": "sax@^1.1.4",
  "_where": "/tmp/d-11685-2562-158z6dv/package.tgz",
  "author": {
    "name": "Isaac Z. Schlueter",
    "email": "i@izs.me",
    "url": "http://blog.izs.me/"
  },
  "bugs": {
    "url": "https://github.com/isaacs/sax-js/issues"
  },
  "contributors": [
    {
      "name": "Isaac Z. Schlueter",
      "email": "i@izs.me"
    },
    {
      "name": "Stein Martin Hustad",
      "email": "stein@hustad.com"
    },
    {
      "name": "Mikeal Rogers",
      "email": "mikeal.rogers@gmail.com"
    },
    {
      "name": "Laurie Harper",
      "email": "laurie@holoweb.net"
    },
    {
      "name": "Jann Horn",
      "email": "jann@Jann-PC.fritz.box"
    },
    {
      "name": "Elijah Insua",
      "email": "tmpvar@gmail.com"
    },
    {
      "name": "Henry Rawas",
      "email": "henryr@schakra.com"
    },
    {
      "name": "Justin Makeig",
      "email": "jmpublic@makeig.com"
    },
    {
      "name": "Mike Schilling",
      "email": "mike@emotive.com"
    }
  ],
  "dependencies": {},
  "description": "An evented streaming XML parser in JavaScript",
  "devDependencies": {
    "standard": "^5.3.1",
    "tap": "^5.2.0"
  },
  "directories": {},
  "dist": {
    "shasum": "7b8e656190b228e81a66aea748480d828cd2d37a",
    "tarball": "https://registry.npmjs.org/sax/-/sax-1.2.1.tgz"
  },
  "files": [
    "lib/sax.js",
    "LICENSE",
    "LICENSE-W3C.html",
    "README.md"
  ],
  "gitHead": "9f9814f544f1c5b89dd1d79957c041f37e845b4a",
  "homepage": "https://github.com/isaacs/sax-js#readme",
  "license": "ISC",
  "main": "lib/sax.js",
  "maintainers": [
    {
      "name": "isaacs",
      "email": "i@izs.me"
    }
  ],
  "name": "sax",
  "optionalDependencies": {},
  "readme": "ERROR: No README data found!",
  "repository": {
    "type": "git",
    "url": "git://github.com/isaacs/sax-js.git"
  },
  "scripts": {
    "posttest": "standard -F test/*.js lib/*.js",
    "test": "tap test/*.js --cov"
  },
  "version": "1.2.1"
}

```
