### ISSUE TITLE
Error: spawn xmllint ENOENT

### ISSUE THREAD

**Issue by fiskr** [AtomLinter/linter-xmllint#60]
#### Background

Installed through Atom's Preferences Pane.

Atom version is `1.0.19`, linter-xmllint version is `1.3.4`.

Operating System is Debian 8, Jessie.

#### Error

```
Error: spawn xmllint ENOENT
  at exports._errnoException (util.js:814:11)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
  at onErrorNT (internal/child_process.js:344:16)
  at doNTCallback2 (node.js:438:9)
  at process._tickCallback (node.js:352:17)
```

#### Screenshot 

![20160601_12-38-01](https://cloud.githubusercontent.com/assets/3150575/15717577/9a0d757e-27f5-11e6-976c-e47345857032.png)

**Comment by fiskr** [comment]
Fixed by running:

```
# apt-get install libxml2-utils
```
