### ISSUE TITLE
Uncaught Error: Unexpected endLine: 2Column: 0Char: 

### ISSUE THREAD

**Issue by xHatchx** [AtomLinter/linter-xmllint#64]
[Enter steps to reproduce below:]

Hmmm... I didn't do anything special. I just had a simple, practically empty xml file that I started working on and always when I saved(or sometimes even when I was typing), it threw out this error.

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.6
**Thrown From**: [linter-xmllint](https://github.com/AtomLinter/linter-xmllint) package, v1.3.5

### Stack Trace

Uncaught Error: Unexpected end
Line: 2
Column: 0
Char: 

```
At events.js:141

Error: Unexpected end
Line: 2
Column: 0
Char: 
  at error (/Users/felixkranich/.atom/packages/linter-xmllint/node_modules/sax/lib/sax.js:667:10)
  at end (/Users/felixkranich/.atom/packages/linter-xmllint/node_modules/sax/lib/sax.js:678:7)
  at Object.SAXParser.end (/Users/felixkranich/.atom/packages/linter-xmllint/node_modules/sax/lib/sax.js:154:24)
  at SAXStream.end (/Users/felixkranich/.atom/packages/linter-xmllint/node_modules/sax/lib/sax.js:248:18)
  at ReadableString.onend (_stream_readable.js:490:10)
  at ReadableString.g (events.js:260:16)
  at emitNone (events.js:67:13)
  at ReadableString.emit (events.js:166:7)
  at endReadableNT (_stream_readable.js:905:12)
  at doNTCallback2 (node.js:465:9)
  at process._tickCallback (node.js:379:17)

```

### Commands

```
     -2:09.9.0 snippets:next-tab-stop (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -2:09.9.0 snippets:expand (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -2:09.9.0 editor:indent (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  2x -2:09.5.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -2:07.6.0 core:save (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -2:06.7.0 settings-view:open (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -2:04.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:45.4.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:45.3.0 snippets:next-tab-stop (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:45.3.0 snippets:expand (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:45.3.0 editor:indent (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  2x -0:44.5.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:00.9.0 snippets:next-tab-stop (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:00.9.0 snippets:expand (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:00.9.0 editor:indent (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:00.4.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "atom-terminal",
      "atom-terminal-panel",
      "open-terminal-here",
      "autocomplete-java",
      "hyperclick",
      "tree-view",
      "omnisharp-atom",
      "activate-power-mode",
      "linter-gcc",
      "linter-jslint",
      "linter-jscs",
      "change-tabs"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      "*.meta",
      "*.o"
    ],
    "packagesWithKeymapsDisabled": [
      "atom-terminal",
      "atom-terminal-panel",
      "open-terminal-here",
      "emmet",
      "sort-lines"
    ],
    "themes": [
      "excellent-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.10
atom-html-preview, v0.1.21
atom-ternjs, v0.14.2
atom-trello, v0.5.1
atom-yeoman, v0.3.15
autocomplete-clang, v0.9.4
autocomplete-computercraft, v1.0.0
autocomplete-emojis, v2.5.0
autocomplete-en-en, v0.2.0
autocomplete-folders, v0.4.1
autocomplete-glsl, v0.2.3
autocomplete-html-entities, v0.1.0
autocomplete-json, v5.1.0
autocomplete-love, v0.3.0
autocomplete-project-paths, v2.2.0
autocomplete-python, v1.8.2
autocomplete-ruby, v0.1.0
autocomplete-xml, v0.8.3
bottom-dock, v0.4.4
close-other-tabs, v0.1.0
color-picker, v2.2.2
documentation-renderer, v0.2.1
emmet, v2.4.3
excellent-ui, v2.2.1
file-types, v0.5.2
haskell-grammar, v0.4.0
highlight-selected, v0.11.2
hyperclick, v0.0.37
hyperclick-love, v0.4.0
java-importer, v1.4.1
json-schema, v0.1.15
language-arduino, v0.4.1
language-babel, v2.32.0
language-common-lisp, v0.8.1
language-csharp, v0.12.1
language-glsl, v2.0.1
language-htaccess, v0.1.1
language-ini, v1.16.0
language-lisp, v0.2.0
language-lua, v0.9.4
language-ocaml, v1.1.2
language-ruby, v0.69.0
language-rust, v0.4.6
language-thrift, v1.0.2
language-unity-shaderlab, v1.0.1
language-x86, v1.0.1
linter, v1.11.14
linter-alex, v3.2.0
linter-clang, v3.4.4
linter-erb, v1.0.2
linter-javac, v1.9.4
linter-jshint, v2.1.0
linter-luaparse, v0.2.0
linter-manager, v0.2.12
linter-mcs, v0.2.0
linter-php, v1.2.0
linter-python, v3.0.4
linter-ruby, v1.2.2
linter-rust, v0.4.6
linter-tslint, v0.10.0
linter-xmllint, v1.3.5
livereload, v0.4.4
love-ide, v0.11.0
maybs-quit, v1.3.0
merge-conflicts, v1.4.4
minimap, v4.24.7
nuclide, v0.157.0
pigments, v0.31.2
process-palette, v0.8.3
python-iresolve, v0.0.3
python-tools, v0.6.8
rails-i18n-autocomplete, v0.4.0
remote-sync, v4.1.2
save-autorun, v0.3.3
tab-switcher, v1.5.3
tab-title, v0.3.3
tidy-tabs, v0.3.0
todo-manager, v0.2.9
tool-bar, v1.0.0
tool-bar-main, v0.0.9
travis-ci-status, v1.1.1
vim-mode, v0.65.1
xml-tools, v0.2.1

# Dev
No dev packages
```

**Comment by dirk-thomas** [comment]
Can you please post the version number of `xmllint`. Please also share one example file which results in the exception for you.

**Comment by dirk-thomas** [comment]
I am closing this for now since there was no response. Please feel free to comment with the requested information and this can be reopened.
