### ISSUE TITLE
Start up error

### ISSUE THREAD

**Issue by Dherrel** [AtomLinter/linter-xmllint#75]
when opening a file this is the error I get from atom. 

Error: spawn xmllint ENOENT
    at getENOENTError (C:\Users\Dylan\.atom\packages\linter-xmllint\node_modules\sb-exec\lib\helpers.js:159:15)
    at ChildProcess.<anonymous> (C:\Users\Dylan\.atom\packages\linter-xmllint\node_modules\sb-exec\lib\index.js:50:46)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by dirk-thomas** [comment]
Which version of the package are you using? What is your setting for `xmllint Executable Path`?

**Comment by Dherrel** [comment]
Never mind I rechecked the path I set up and realized it was wrong and now the program is working thank you for getting back to me.

**Comment by dirk-thomas** [comment]
If the problem has been resolved for you can you please close this ticket?
