### ISSUE TITLE
xmllint error

### ISSUE THREAD

**Issue by hansonrichardj** [AtomLinter/linter-xmllint#76]
uninstalled, reinstalled xmllint
uninstalled, reinstalled Atom
Always get this error when xmllint is used

**Error: spawn xmllint ENOENT**

Error: spawn xmllint ENOENT
    at getENOENTError (C:\Users\rjhanson\.atom\packages\linter-xmllint\node_modules\sb-exec\lib\helpers.js:159:15)
    at ChildProcess.<anonymous> (C:\Users\rjhanson\.atom\packages\linter-xmllint\node_modules\sb-exec\lib\index.js:50:46)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

Dell Precision 7510 laptop
Windows 7
Intel I7 processor
32 GB RAM

new to Atom so I am no help, but could use some help

**Comment by dirk-thomas** [comment]
Is `xmllint` on your `PATH`? Can you invoke it on the command line?

**Comment by hansonrichardj** [comment]
Very interesting.  I did not know that xmllint when installed by Atom did not add it to the path, nor told me to add it to the path.
However, I located xmllint.exe and added the path and is now working correctly.
Thank you for the assistance.  I will now check any packaged for the issue if they do not work correctly
 

    On Friday, February 24, 2017 9:15 AM, Dirk Thomas <notifications@github.com> wrote:
 

 Is xmllint on your PATH? Can you invoke it on the command line?—

**Comment by dirk-thomas** [comment]
Since the [README](https://github.com/AtomLinter/linter-xmllint/blob/master/README.md) covers this case can you please close this ticket?
