### ISSUE TITLE
Error running xmllint Error: Cannot find module 'tmp'

### ISSUE THREAD

**Issue by tarnagas** [AtomLinter/linter-xmllint#83]
```
[Linter] Error running xmllint Error: Cannot find module 'tmp'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/src/module-cache.js:354:58)
    at Module.require (file:///usr/share/atom/resources/app/static/index.js:40:43)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/home/dimitri/.atom/packages/linter-xmllint/node_modules/atom-linter/lib/helpers.js:23:12)
    at Object.<anonymous> (/home/dimitri/.atom/packages/linter-xmllint/node_modules/atom-linter/lib/helpers.js:139:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///usr/share/atom/resources/app/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/home/dimitri/.atom/packages/linter-xmllint/node_modules/atom-linter/lib/index.js:139:16)
    at Object.<anonymous> (/home/dimitri/.atom/packages/linter-xmllint/node_modules/atom-linter/lib/index.js:329:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///usr/share/atom/resources/app/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.checkWellFormed (/home/dimitri/.atom/packages/linter-xmllint/lib/init.coffee:93:16)
    at Object.lintOpenFile (/home/dimitri/.atom/packages/linter-xmllint/lib/init.coffee:83:28)
    at Object.provider.lint (/home/dimitri/.atom/packages/linter-xmllint/lib/init.coffee:80:17)
    at promises.push.Promise.then._this2.emitter.emit.number (/home/dimitri/.atom/packages/linter/lib/linter-registry.js:101:24)
    at _loop (/home/dimitri/.atom/packages/linter/lib/linter-registry.js:99:21)
    at LinterRegistry.<anonymous> (/home/dimitri/.atom/packages/linter/lib/linter-registry.js:87:40)
    at Generator.next (<anonymous>)
    at LinterRegistry.<anonymous> (/home/dimitri/.atom/packages/linter/lib/linter-registry.js:143:4)
    at Generator.next (<anonymous>)
    at step (/home/dimitri/.atom/packages/linter/lib/linter-registry.js:5:273)
    at /home/dimitri/.atom/packages/linter/lib/linter-registry.js:5:443
    at LinterRegistry.<anonymous> (/home/dimitri/.atom/packages/linter/lib/linter-registry.js:5:99)
    at /home/dimitri/.atom/packages/linter/lib/main.js:125:30
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at EditorLinter.lint (/home/dimitri/.atom/packages/linter/lib/editor-linter.js:40:18)
    at EditorRegistry.createFromTextEditor (/home/dimitri/.atom/packages/linter/lib/editor-registry.js:43:20)
    at /home/dimitri/.atom/packages/linter/lib/editor-registry.js:25:12
    at Workspace.observeTextEditors (/usr/share/atom/resources/app/src/workspace.js:717:15)
    at EditorRegistry.activate (/home/dimitri/.atom/packages/linter/lib/editor-registry.js:24:43)
    at Linter.registryEditorsInit (/home/dimitri/.atom/packages/linter/lib/main.js:132:26)
    at Linter.registryEditorsIdleInit (/home/dimitri/.atom/packages/linter/lib/main.js:103:14)
```

```sh
# uname -psr
Linux 4.10.0-33-generic x86_64
```

```sh
# atom --version
Atom    : 1.19.5
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

**Comment by Arcanemagus** [comment]
Can you try re-installing the package? Rarely APM fails to properly install all dependencies.

**Comment by tarnagas** [comment]
It seems to work… thanks.
