### ISSUE TITLE
Uncaught Error: Unexpected endLine: 0Column: 5Char: 

### ISSUE THREAD

**Issue by yanivk** [AtomLinter/linter-xmllint#85]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.0 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [linter-xmllint](https://github.com/AtomLinter/linter-xmllint) package 1.4.3

### Stack Trace

Uncaught Error: Unexpected end
Line: 0
Column: 5
Char: 

```
At events.js:160

Error: Unexpected end
Line: 0
Column: 5
Char: 
    at error (/packages/linter-xmllint/node_modules/sax/lib/sax.js:651:10)
    at end (/packages/linter-xmllint/node_modules/sax/lib/sax.js:662:7)
    at SAXParser.end (/packages/linter-xmllint/node_modules/sax/lib/sax.js:154:24)
    at SAXStream.end (/packages/linter-xmllint/node_modules/sax/lib/sax.js:248:18)
    at ReadableString.onend (_stream_readable.js:511:10)
    at Object.onceWrapper (events.js:290:19)
    at emitNone (events.js:86:13)
    at ReadableString.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -2:25.7.0 application:add-project-folder (input.hidden-input)
     -2:12.9.0 core:confirm (input.hidden-input)
     -0:43.6.0 tree-view:add-file (div.header.list-item.project-root-header)
     -0:35 core:confirm (input.hidden-input)
     -0:08.2.0 editor:newline (input.hidden-input)
     -0:08.0 intentions:highlight (input.hidden-input)
     -0:07.9.0 core:paste (input.hidden-input)
  3x -0:03.9.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.5.3 
busy-signal 1.4.3 
data-atom 0.26.2 
hyperclick 0.0.0 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.6.10 
linter-xmllint 1.4.3 
php-integrator-autocomplete-plus 1.6.1 
php-integrator-base 3.1.0 
php-integrator-navigation 1.2.1 
php-twig 4.0.0 
platformio-ide-terminal 2.7.0 
project-manager 3.3.5 
```

**Comment by dirk-thomas** [comment]
Please provide the steps to reproduce the problem. I will close the ticket for now. Once you have commented with the necessary information this can be reopened.
