### ISSUE TITLE
Uncaught Error: Invalid character entityLine: 8Column: 31Char: ;

### ISSUE THREAD

**Issue by Dynnammo** [AtomLinter/linter-xmllint#90]
Hello guys,
I'm using linter xmllint since a few days, here is the config. 

**Atom**: 1.24.0 x64
**Electron**: 1.6.16
**OS**: Ubuntu 16.04.3
**Thrown From**: [linter-xmllint](https://github.com/AtomLinter/linter-xmllint) package 1.4.3

*Atom is throwing me this message any time i'm doing something in a .xml file. Can someone help me?*

### Stack Trace

Uncaught Error: Invalid character entity
Line: 8
Column: 31
Char: ;

```
At events.js:160

Error: Invalid character entity
Line: 8
Column: 31
Char: ;
    at error (/packages/linter-xmllint/node_modules/sax/lib/sax.js:651:10)
    at strictFail (/packages/linter-xmllint/node_modules/sax/lib/sax.js:677:7)
    at parseEntity (/packages/linter-xmllint/node_modules/sax/lib/sax.js:937:7)
    at SAXParser.write (/packages/linter-xmllint/node_modules/sax/lib/sax.js:1485:31)
    at SAXStream.write (/packages/linter-xmllint/node_modules/sax/lib/sax.js:239:18)
    at ReadableString.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at ReadableString.emit (events.js:188:7)
    at ReadableString.Readable.read (_stream_readable.js:381:10)
    at flow (_stream_readable.js:761:34)
    at resume_ (_stream_readable.js:743:3)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by dirk-thomas** [comment]
Can you provide the file you are trying to line (e.g. via a gist) and the output you get when running `xmllint` with that file on the command line.

**Comment by dirk-thomas** [comment]
Closing due to no response.
