### ISSUE TITLE
Uncaught Error: Unexpected endLine: 45Column: 0Char: 

### ISSUE THREAD

**Issue by Abonia1** [AtomLinter/linter-xmllint#96]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.0 x64
**Electron**: 2.0.3
**OS**: Unknown Windows version
**Thrown From**: [linter-xmllint](https://github.com/AtomLinter/linter-xmllint) package 1.4.4

### Stack Trace

Uncaught Error: Unexpected end
Line: 45
Column: 0
Char: 

```
At events.js:183

Error: Unexpected end
Line: 45
Column: 0
Char: 
    at error (/packages/linter-xmllint/node_modules/sax/lib/sax.js:651:10)
    at end (/packages/linter-xmllint/node_modules/sax/lib/sax.js:662:7)
    at SAXParser.end (/packages/linter-xmllint/node_modules/sax/lib/sax.js:154:24)
    at SAXStream.end (/packages/linter-xmllint/node_modules/sax/lib/sax.js:248:18)
    at ReadableString.onend (_stream_readable.js:595:10)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at ReadableString.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
```

### Non-Core Packages

```
git-plus 7.10.0 
linter 2.0.0 
linter-ui-default 1.7.1 
linter-xmllint 1.4.4 
platformio-ide-terminal 2.8.0 
```

**Comment by dirk-thomas** [comment]
It seems like you missed filling out the steps to reproduce. Please do so and the issue can be reopened.
