### ISSUE TITLE
Uncaught Error: Non-whitespace before first tag.Line: 0Column: 2Char: /

### ISSUE THREAD

**Issue by Jophilga** [AtomLinter/linter-xmllint#97]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.0 x64
**Electron**: 2.0.3
**OS**: Unknown Windows version
**Thrown From**: [linter-xmllint](https://github.com/AtomLinter/linter-xmllint) package 1.4.4

### Stack Trace

Uncaught Error: Non-whitespace before first tag.
Line: 0
Column: 2
Char: /

```
At events.js:183

Error: Non-whitespace before first tag.
Line: 0
Column: 2
Char: /
    at error (/packages/linter-xmllint/node_modules/sax/lib/sax.js:651:10)
    at strictFail (/packages/linter-xmllint/node_modules/sax/lib/sax.js:677:7)
    at beginWhiteSpace (/packages/linter-xmllint/node_modules/sax/lib/sax.js:951:7)
    at SAXParser.write (/packages/linter-xmllint/node_modules/sax/lib/sax.js:1010:11)
    at SAXStream.write (/packages/linter-xmllint/node_modules/sax/lib/sax.js:239:18)
    at ReadableString.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at ReadableString.emit (events.js:211:7)
    at ReadableString.Readable.read (_stream_readable.js:475:10)
    at flow (_stream_readable.js:846:34)
    at resume_ (_stream_readable.js:828:3)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
```

### Non-Core Packages

```
atom-ide-ui 0.12.0 
language-dtd 0.2.1 
linter 2.2.0 
linter-xmllint 1.4.4 
```

**Comment by dirk-thomas** [comment]
It seems like you missed filling out the steps to reproduce. Please do so and the issue can be reopened.
